package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

type Config struct {
	DetectionPackage    string `json:"detectionPackage"`
	DetectionStructName string `json:"detectionStructName"`
	DTSVar              string `json:"dtsVar"`
	DTBMVar             string `json:"dtbmVar"`
	HasRAMFallback      bool   `json:"hasRamFallback"`
	BoardtypeImport     string `json:"boardtypeImport"`
}

type BoardEntry struct {
	VarName      string `json:"varName"`
	Manufacturer string `json:"manufacturer"`
	Model        string `json:"model"`
	SubModel     string `json:"subModel"`
	RAM          int    `json:"ram"`
	SOC          string `json:"soc"`
	Parent       string `json:"parent"`
}

type DTSEntry struct {
	Pattern string `json:"pattern"`
	Board   string `json:"board"`
}

type DTBMEntry struct {
	Pattern  string `json:"pattern"`
	Board    string `json:"board"`
	Memory   int    `json:"memory"`
	Fallback string `json:"fallback"`
}

type Schema struct {
	Config      Config       `json:"config"`
	Boards      []BoardEntry `json:"boards"`
	DTSEntries  []DTSEntry   `json:"dtsEntries"`
	DTBMEntries []DTBMEntry  `json:"dtbmEntries"`
}

type boardsData struct {
	InputFile string
	Boards    []BoardEntry
}

type detectionData struct {
	InputFile   string
	Config      Config
	DTSEntries  []DTSEntry
	DTBMEntries []DTBMEntry
}

var boardsTmpl = template.Must(template.New("boards").Parse(
	`// Code generated by cmd/generate. DO NOT EDIT.
// Source: {{.InputFile}} — run: go generate ./boardtype/...

package boardtype

var (
{{range .Boards}}	{{.VarName}} = BoardType{Manufacturer: {{printf "%q" .Manufacturer}}, Model: {{printf "%q" .Model}}, SubModel: {{printf "%q" .SubModel}}, RAM: {{.RAM}}{{if .SOC}}, SOC: {{printf "%q" .SOC}}{{end}}{{if .Parent}}, BaseModel: &{{.Parent}}{{end}}}
{{end}})
`))

var detectionTmpl = template.Must(template.New("detection").Parse(
	`// Code generated by cmd/generate. DO NOT EDIT.
// Source: {{.InputFile}} — run: go generate ./boardtype/...

package {{.Config.DetectionPackage}}

{{if or .DTSEntries .DTBMEntries}}import "{{.Config.BoardtypeImport}}"
{{end}}
{{if and .Config.DTSVar .DTSEntries}}var {{.Config.DTSVar}} = []{{.Config.DetectionStructName}}{
{{range .DTSEntries}}	{"{{.Pattern}}", boardtype.{{.Board}}},
{{end}}}
{{end}}
{{if and .Config.DTBMVar .DTBMEntries}}var {{.Config.DTBMVar}} = []{{.Config.DetectionStructName}}{
{{range .DTBMEntries}}{{if $.Config.HasRAMFallback}}	{"{{.Pattern}}", {{.Memory}}, boardtype.{{.Board}}, boardtype.{{.Fallback}}},
{{else}}	{"{{.Pattern}}", boardtype.{{.Board}}},
{{end}}{{end}}}
{{end}}`))

func validate(schema *Schema) error {
	byName := make(map[string]bool, len(schema.Boards))
	for _, b := range schema.Boards {
		if byName[b.VarName] {
			return fmt.Errorf("duplicate varName: %s", b.VarName)
		}
		byName[b.VarName] = true
	}
	for _, b := range schema.Boards {
		if b.Parent != "" && !byName[b.Parent] {
			return fmt.Errorf("board %s: unknown parent %q", b.VarName, b.Parent)
		}
	}
	for _, e := range schema.DTSEntries {
		if !byName[e.Board] {
			return fmt.Errorf("dtsEntry %q: unknown board %q", e.Pattern, e.Board)
		}
	}
	for _, e := range schema.DTBMEntries {
		if !byName[e.Board] {
			return fmt.Errorf("dtbmEntry %q: unknown board %q", e.Pattern, e.Board)
		}
		if schema.Config.HasRAMFallback && e.Fallback != "" && !byName[e.Fallback] {
			return fmt.Errorf("dtbmEntry %q: unknown fallback %q", e.Pattern, e.Fallback)
		}
	}
	return nil
}

func topoSort(boards []BoardEntry) ([]BoardEntry, error) {
	idx := make(map[string]int, len(boards))
	for i, b := range boards {
		idx[b.VarName] = i
	}

	children := make(map[string][]string, len(boards))
	inDegree := make(map[string]int, len(boards))
	for _, b := range boards {
		inDegree[b.VarName] = 0
	}
	for _, b := range boards {
		if b.Parent != "" {
			children[b.Parent] = append(children[b.Parent], b.VarName)
			inDegree[b.VarName]++
		}
	}

	queue := make([]string, 0, len(boards))
	for _, b := range boards {
		if inDegree[b.VarName] == 0 {
			queue = append(queue, b.VarName)
		}
	}

	sorted := make([]BoardEntry, 0, len(boards))
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		sorted = append(sorted, boards[idx[name]])
		for _, child := range children[name] {
			inDegree[child]--
			if inDegree[child] == 0 {
				queue = append(queue, child)
			}
		}
	}

	if len(sorted) != len(boards) {
		return nil, fmt.Errorf("cycle detected in board hierarchy")
	}
	return sorted, nil
}

func render(tmpl *template.Template, data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("go/format: %w\n---\n%s", err, buf.Bytes())
	}
	return src, nil
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func main() {
	input := flag.String("input", "", "path to JSON board definitions file")
	boardsOut := flag.String("boards-out", "", "path to write generated board vars Go file")
	detectionOut := flag.String("detection-out", "", "path to write generated detection tables Go file")
	flag.Parse()

	if *input == "" || *boardsOut == "" || *detectionOut == "" {
		fmt.Fprintln(os.Stderr, "usage: generate -input <file> -boards-out <file> -detection-out <file>")
		os.Exit(1)
	}

	raw, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading %s: %v\n", *input, err)
		os.Exit(1)
	}

	var schema Schema
	if err := json.Unmarshal(raw, &schema); err != nil {
		fmt.Fprintf(os.Stderr, "error parsing %s: %v\n", *input, err)
		os.Exit(1)
	}

	if err := validate(&schema); err != nil {
		fmt.Fprintf(os.Stderr, "validation error in %s: %v\n", *input, err)
		os.Exit(1)
	}

	sorted, err := topoSort(schema.Boards)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error in %s: %v\n", *input, err)
		os.Exit(1)
	}

	boardsSrc, err := render(boardsTmpl, boardsData{
		InputFile: filepath.Base(*input),
		Boards:    sorted,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error generating boards: %v\n", err)
		os.Exit(1)
	}
	if err := writeFile(*boardsOut, boardsSrc); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", *boardsOut, err)
		os.Exit(1)
	}

	detectionSrc, err := render(detectionTmpl, detectionData{
		InputFile:   filepath.Base(*input),
		Config:      schema.Config,
		DTSEntries:  schema.DTSEntries,
		DTBMEntries: schema.DTBMEntries,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error generating detection: %v\n", err)
		os.Exit(1)
	}
	if err := writeFile(*detectionOut, detectionSrc); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", *detectionOut, err)
		os.Exit(1)
	}

	fmt.Printf("generated %s and %s from %s\n", *boardsOut, *detectionOut, *input)
}
