// Code generated by cmd/generate. DO NOT EDIT.
// Source: nvidia.json — run: go generate ./boardtype/...

package nvidia

import "github.com/rinzlerlabs/sbcidentify/boardtype"

var jetsonModulesByModelNumber = []jetson{
	{"p3767-0000", boardtype.JetsonOrinNX16GB},
	{"p3767-0001", boardtype.JetsonOrinNX8GB},
	{"p3767-0003", boardtype.JetsonOrinNano8GB},
	{"p3767-0004", boardtype.JetsonOrinNano4GB},
	{"p3767-0005", boardtype.JetsonOrinNanoDeveloperKit},
	{"p3701-0000", boardtype.JetsonAGXOrin},
	{"p3701-0004", boardtype.JetsonAGXOrin32GB},
	{"p3701-0005", boardtype.JetsonAGXOrin64GB},
	{"p3668-0000", boardtype.JetsonXavierNXDeveloperKit},
	{"p3668-0001", boardtype.JetsonXavierNX8GB},
	{"p3668-0003", boardtype.JetsonXavierNX16GB},
	{"p2972-0000", boardtype.JetsonAGXXavier},
	{"p2888-0006", boardtype.JetsonAGXXavier8GB},
	{"p2888-0001", boardtype.JetsonAGXXavier16GB},
	{"p2888-0003", boardtype.JetsonAGXXavier32GB},
	{"p2888-0004", boardtype.JetsonAGXXavier32GB},
	{"p2888-0005", boardtype.JetsonAGXXavier64GB},
	{"p2888-0008", boardtype.JetsonAGXXavierIndustrial32GB},
	{"p3450-0000", boardtype.JetsonNanoDeveloperKit},
	{"p3448-0003", boardtype.JetsonNano2GB},
	{"p3448-0002", boardtype.JetsonNano16GbEMMC},
	{"p3448-0000", boardtype.JetsonNano4GB},
	{"p2771-0000", boardtype.JetsonTX2},
	{"p3310-1000", boardtype.JetsonTX2},
	{"p3489-0000", boardtype.JetsonTX2i},
	{"p3489-0888", boardtype.JetsonTX24GB},
	{"p3636-0001", boardtype.JetsonTX2NX},
	{"p3509-0000", boardtype.JetsonTX2NX},
	{"p2180-1000", boardtype.JetsonTX1},
	{"p2371-2180", boardtype.JetsonTX1},
	{"p3904-0000", boardtype.ClaraAGX},
	{"p2894-0050", boardtype.ShieldTV},
}

var jetsonModulesByDeviceTreeBaseModel = []jetson{
	{"NVIDIA Jetson Orin NX Engineering Reference Developer Kit", boardtype.JetsonOrinNX16GB},
	{"NVIDIA Jetson Orin Nano Developer Kit", boardtype.JetsonOrinNanoDeveloperKit},
	{"NVIDIA Jetson AGX Orin Developer Kit", boardtype.JetsonAGXOrin},
	{"NVIDIA Jetson AGX Orin", boardtype.JetsonAGXOrin},
	{"NVIDIA Jetson Xavier NX Developer Kit (SD-card)", boardtype.JetsonXavierNXDeveloperKit},
	{"NVIDIA Jetson Xavier NX Developer Kit (eMMC)", boardtype.JetsonXavierNXDeveloperKit},
	{"NVIDIA Jetson Xavier NX (SD-card)", boardtype.JetsonXavierNXDeveloperKit},
	{"NVIDIA Jetson Xavier NX (eMMC)", boardtype.JetsonXavierNX8GB},
	{"NVIDIA Jetson AGX Xavier", boardtype.JetsonAGXXavier},
	{"NVIDIA Jetson AGX Xavier Developer Kit", boardtype.JetsonAGXXavier},
	{"NVIDIA Jetson Nano Developer Kit", boardtype.JetsonNanoDeveloperKit},
	{"NVIDIA Jetson TX2 Developer Kit", boardtype.JetsonTX2},
	{"NVIDIA Jetson TX2", boardtype.JetsonTX2},
	{"NVIDIA Jetson TX2 NX Developer Kit", boardtype.JetsonTX2NX},
	{"NVIDIA Jetson TX1", boardtype.JetsonTX1},
	{"NVIDIA Jetson TX1 Developer Kit", boardtype.JetsonTX1},
	{"NVIDIA Shield TV", boardtype.ShieldTV},
}
