name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      
      - name: Verify generated files are up to date
        run: |
          go generate ./boardtype/...
          git diff --exit-code
      
      - name: Verify files are formatted
        run: |
          gofmt -w .
          git diff --exit-code
      
      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      
